# fly.toml file generated for pokedex-fso on 2023-02-28T17:17:44+01:00

app = "pokedex-fso"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []


[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.script_checks]]
    
    grace_period = "2s"
    interval = "10s"
    restart_limit = 0
    timeout = "1s"

  [[services.http_checks]]
    grace_period = "10s"
    interval = "10s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = "2s"
    [services.http_checks.headers]