name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say Hello
        run: |
          echo "Heollo World!"
      - name: Current Date
        run: |
          echo date
      - name: Current Directory
        run: |
          echo ls -l
